export const titleContentConfig = {
  services: {
    title: "Dedicated Fulfillment Solutions\n",
    highlight: "That Power Your Growth",
    content: "",
    titleTag: "h2",
    contentTag: "p",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[1.125rem]",
    titleColor: "#212121",
    contentColor: "#4A4A4A",
  },

  brand: {
    title: "Trusted by 1,100+ fast-growing brands",
    highlight: "1,100+",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
  },

  WhyChoose: {
    title: "Why Leading Brands Trust Depoter",
    highlight: "Depoter",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },

  Scalability: {
    title: "Scalability You Can Measure",
    highlight: "Measure",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  Howtowork: {
    title: "How Depoter Works",
    highlight: "Works",
    content:
      "Our connected process links your store, organizes your inventory, and delivers your orders quickly and accurately without operational complexity.",
    titleTag: "h2",
    contentTag: "p",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[1.125rem]",
    titleColor: "#212121",
    contentColor: "#000000",
  },
  buildtohandle: {
    title: "Built to Handle What You Sell",
    highlight: "Sell",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  global: {
    title: "Global Network of Fulfilment Centres",
    highlight: "Fulfilment Centres",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  insights: {
    title: "Insights from the Fulfillment Floor",
    highlight: "Fulfillment Floor",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  testimonials: {
    title: "Deeds Over Words",
    highlight: "Over Words",
    content: "What Our Clients Say",
    titleTag: "h2",
    contentTag: "h3",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[2rem]",
    titleColor: "#212121",
    contentColor: "#212121",
  },
  case: {
    title: "Delivered by Depoter",
    highlight: "Depoter",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  buildtohandleservice: {
    title: "Built to Handle What You Sell",
    highlight: "You Sell",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  Fulfillmentcenter: {
    title: "How Orders Move Through Our\n D2C Fulfillment Center",
    highlight: "D2C Fulfillment Center",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  easyreturns: {
    title: "Easy Returns and Exchanges",
    highlight: "and Exchanges",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  flexible: {
    title: " The Pillars of Fast and Flexible\n D2C Fulfillment",
    highlight: "D2C Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  Businessinsync: {
    title: "Integration That Keeps Your \n Business in Sync",
    highlight: "Business in Sync",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
    content:
      "Our platform integrates with leading eCommerce platforms, marketplaces, and shipping providers, automating order flow, inventory updates, and shipment tracking.",
    contentTag: "p",
    contentSize: "text-[1.125rem]",
    contentColor: "#FFFFFF",
  },
  Crossdocking: {
    title: "Crossdocking \n for Rapid ",
    highlight: "D2C \n Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  whychoosedepoter: {
    title: "Why Choose Depoter \n for ",
    highlight: "Freezone \n Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
  },
};
