import { button } from "framer-motion/client";

export const titleContentConfig = {
  services: {
    title: "Dedicated Fulfillment Solutions\n",
    highlight: "That Power Your Growth",
    content: "",
    titleTag: "h2",
    contentTag: "p",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[1.125rem]",
    titleColor: "#212121",
    contentColor: "#4A4A4A",
  },

  brand: {
    title: "Trusted by 1,100+ fast-growing brands",
    highlight: "1,100+",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
  },

  WhyChoose: {
    title: "Why Leading Brands Trust Depoter",
    highlight: "Depoter",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },

  Scalability: {
    title: "Scalability You Can Measure",
    highlight: "Measure",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  Howtowork: {
    title: "How Depoter Works",
    highlight: "Works",
    content:
      "Our connected process links your store, organizes your inventory, and delivers your orders quickly and accurately without operational complexity.",
    titleTag: "h2",
    contentTag: "p",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[1.125rem]",
    titleColor: "#212121",
    contentColor: "#000000",
  },
  buildtohandle: {
    title: "Built to Handle What You Sell",
    highlight: "Sell",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  global: {
    title: "Global Network of Fulfilment Centres",
    highlight: "Fulfilment Centres",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  insights: {
    title: "Insights from the Fulfillment Floor",
    highlight: "Fulfillment Floor",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  testimonials: {
    title: "Deeds Over Words",
    highlight: "Over Words",
    content: "What Our Clients Say",
    titleTag: "h2",
    contentTag: "h3",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[2rem]",
    titleColor: "#212121",
    contentColor: "#212121",
  },
  case: {
    title: "Delivered by Depoter",
    highlight: "Depoter",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  buildtohandleservice: {
    title: "Built to Handle What You Sell",
    highlight: "You Sell",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },

  betterchoicemultichannel: {
    title: "Built to Handle What You Sell",
    highlight: "You Sell",
    title: "What Makes Us\n ",
    highlight: "the Better Choice",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },

  Fulfillmentcenter: {
    title: "How Orders Move Through Our\n D2C Fulfillment Center",
    highlight: "D2C Fulfillment Center",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },

  addvaluetosupplychain: {
    title: "How Depoter Adds\n",
    highlight: "Value to Your Supply Chain",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#FFFFFF",
    content:
      "Businesses involved in international trade often face challenges related to shipping complexity, regulatory requirements, and unpredictable logistics costs.Depoter focuses on solving these challenges through structured logistics solutions designed for operational efficiency.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#FFFFFF",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
  },

  handleEveryOrder: {
    title: "How We Handle\n",
    highlight: "Every Order",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    content:
      "We handle every order with care, from inspection and labeling to storage, picking, packing, and dispatch. Our workflows deliver reliable multi-channel fulfillment services and e-commerce warehouse fulfillment for Amazon and Noon, ensuring seamless multi-channel order fulfillment for Amazon and Noon sellers",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
  },

  freightforwardingservices: {
    title: "Our Freight ",
    highlight: "Forwarding Services",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    content:
      "Depoter provides a comprehensive suite of freight solutions designed to support businesses engaged in global trade.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
  },

  returnandexchange: {
    title: "Returns and Exchange\n",
    highlight: "That Flow Smoothly",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
  },

  seamlessnoonorder: {
    title: "Seamless Fulfillment for Your \n",
    highlight: "Noon Orders",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    content:
      "As a trusted Noon fulfillment partner, we handle storage, order fulfillment, delivery, and returns for both FBN and Direct Ship models across the UAE, KSA, and Egypt, enabling sellers to scale without operational complexity.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#FFFFFF",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
    titleColor: "#ffffff",
  },

  whybusinesschoosedepoter: {
    title: "Why Businesses ",
    highlight: "Choose Depoter",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    content:
      "Selecting a freight forwarding partner is an important decision that directly impacts supply chain reliability.Companies choose Depoter because of our experience, industry expertise, and structured logistics approach.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#212121",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
    titleColor: "#212121",
  },

  customsclearance: {
    title: "Our Customs Clearance ",
    highlight: "Services in UAE",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    content:
      "Every shipment is different — that’s why we provide customized solutions based on your cargo type, port, and requirements.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#212121",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
    titleColor: "#212121",
  },

  portsairportscoverage: {
    title: "Ports & Airports ",
    highlight: "We Cover in UAE",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    content:
      "The UAE is a global logistics hub, and each gateway has its own unique customs process.Depoter provides expert on-ground support across all major locations.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#212121",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
    titleColor: "#212121",
  },

  customclearanceprocesswork: {
    title: "How Our Customs ",
    highlight: "Clearance\n Process Works",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    content:
      "We follow a simple and structured process to ensure your shipment is cleared quickly and accurately.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#212121",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
    titleColor: "#212121",
  },

  whychoosedepotercustomclearance: {
    title: "Why Choose ",
    highlight: "Depoter for Customs\n Clearance Services in UAE",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    content:
      "We follow a simple and structured process to ensure your shipment is cleared quickly and accurately.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#FFFFFF",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
    titleColor: "#FFFFFF",
  },

  whoweserve: {
    title: "Who We ",
    highlight: "Serve",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#FFFFFF",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
    titleColor: "#212121",
  },

  FulfillmentCenterWorks: {
    title: "How Our ",
    highlight: "Fulfillment Center Works",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    content:
      "A structured workflow is what ensures inventory accuracy and fast shipping. Here is a look at our end-to-end process:",
    contentColor: "#212121",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
    titleColor: "#212121",
  },

  automatedorderflow: {
    title: "Tailor-Made Technology &\n",
    highlight: "Automated Order Flow",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    content:
      "A structured workflow is what ensures inventory accuracy and fast shipping. Here is a look at our end-to-end process:",
    contentColor: "#ffffff",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
    titleColor: "#ffffff",
  },

  efficientstorage: {
    title: "Efficient Storage\n",
    highlight: "Architecture",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    content:
      "Space utilization is a science at Depoter. Our logistics infrastructure is engineered to reduce movement time and increase productivity.",
    highlightColor: "#ffbe2e",
    contentAlign: "right",
    contentColor: "#212121",
    contentSize: "text-[1.3rem]",
    // contentWidth: "w-full md:w-3/4 lg:w-2/3",
    titleColor: "#212121",
  },

  climatestoragecontrol: {
    title: "Climate-Controlled Storage for\n",
    highlight: "Product Safety",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    content:
      "Space utilization is a science at Depoter. Our logistics infrastructure is engineered to reduce movement time and increase productivity.",
    highlightColor: "#ffbe2e",
    contentAlign: "right",
    contentColor: "#212121",
    contentSize: "text-[1.3rem]",
    // contentWidth: "w-full md:w-3/4 lg:w-2/3",
    titleColor: "#212121",
  },

  amazonfulfillment: {
    title: "Amazon Fulfillment That Keeps\n",
    highlight: "Your Business Moving",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    content:
      "We support Amazon sellers across FBA, FBM, EasyShip, and Vendor Central models. Our teams manage labeling, inbound planning, order processing, shipping coordination, and compliance to ensure reliable e-commerce fulfillment and consistent marketplace performance.",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#FFFFFF",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
  },

  strategichubforglobal: {
    title: "Dubai: ",
    highlight: "A Strategic Hub for Global Freight",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "black",
    highlightColor: "#ffbe2e",
    contentAlign: "center",
    contentColor: "#FFFFFF",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
  },

  customclearance: {
    title: "Customs ",
    highlight: "Clearance & Documentation",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "black",
    highlightColor: "#ffbe2e",
    content:
      "International trade requires strict compliance with customs regulations, accurate documentation, and proper product classification.Our customs specialists help businesses manage the complexities of import and export procedures by handling essential documentation such as:",
    contentAlign: "center",
    contentColor: "black",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
  },

  industriesweserve: {
    title: "Industries  ",
    highlight: "We Serve",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "black",
    highlightColor: "#ffbe2e",
    content:
      "Depoter supports businesses across multiple industries that rely on efficient global logistics and reliable cargo transportation.",
    contentAlign: "center",
    contentColor: "black",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
  },

  strategicallylocated: {
    title: "Strategically Located Warehouses\n for ",
    highlight: "Faster Deliveries",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "black",
    highlightColor: "#ffbe2e",
    // contentAlign: "right",
    contentColor: "black",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
  },

  strategicallylocated: {
    title: "Strategically Located Warehouses\n for ",
    highlight: "Faster Deliveries",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "black",
    highlightColor: "#ffbe2e",
    // contentAlign: "right",
    contentColor: "black",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
  },

  westoreanything: {
    title: "We Store ",
    highlight: "Anything You Sell",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
    content:
      "Our 3PL fulfillment services are industry-agnostic. We have built a flexible storage environment that can handle diverse product categories without complexity.",
    contentAlign: "center",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
    contentColor: "white",
    contentWidth: "w-full md:w-3/4 lg:w-4/5",
  },

  stepbystepfreightprocess: {
    title: "Step-by-Step ",
    highlight: "Freight Process",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "black",
    highlightColor: "#ffbe2e",
    content:
      "To ensure a smooth logistics experience for our clients, Depoter follows a structured freight management process.",
    contentAlign: "center",
    contentColor: "black",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
  },

  shippingwithconfidence: {
    title: "Start Shipping with ",
    highlight: "Confidence",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "white",
    highlightColor: "#ffbe2e",
    content:
      "Simplify your international shipping with a reliable freight partner. Depoter ensures smooth, fast, and compliant cargo movement across global routes.",
    contentAlign: "center",
    contentColor: "white",
    contentWidth: "w-full md:w-3/4 lg:w-5/7",
  },

  easyreturns: {
    title: "Easy Returns and Exchanges",
    highlight: "and Exchanges",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },

  flexible: {
    title: " The Pillars of Fast and Flexible\n D2C Fulfillment",
    highlight: "D2C Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },

  Businessinsync: {
    title: "Integration That Keeps Your \n Business in Sync",
    highlight: "Business in Sync",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
    content:
      "Our platform integrates with leading eCommerce platforms, marketplaces, and shipping providers, automating order flow, inventory updates, and shipment tracking.",
    contentTag: "p",
    contentSize: "text-[1.125rem]",
    contentColor: "#FFFFFF",
  },

  Crossdocking: {
    title: "Crossdocking \n for Rapid ",
    highlight: "D2C \n Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  whychoosedepoter: {
    title: "Why Choose Depoter \n for ",
    highlight: "Freezone \n Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
  },
  b2bgradient: {
    title: "The Numbers That Define Us",
    highlight: "Define Us",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  smarttechnology: {
    title: "Smart Technology That \n Simplifies Every B2B Order",
    highlight: "B2B Order",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  flexiblestorage: {
    title: "Flexible Storage Solutions \n for Every Product Type",
    content:
      "Our warehouse facilities are equipped to manage all types of goods under precise environmental conditions. Our warehouse services include temperature-controlled zones, chiller storage, and compliance-ready facilities for specialized products.",
    highlight: "Product Type",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
    contentColor: "#000000",
  },
  fasterexpansion: {
    title: "Your Gateway to Duty-Free Storage \n and Faster GCC Expansion",
    highlight: "Faster GCC Expansion",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  managemesaurment: {
    title: "Manage Multiple Units of \n Measurement with Total Control",
    highlight: "Total Control",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
    content:
      "Our advanced inventory management system is designed for flexibility and accuracy. It handles multiple measurement levels seamlessly so that you can sell and ship products in any format without manual conversions.",
    contentColor: "#000000",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
  },
  deliverretail: {
    title: "Deliver to Every Retail Shelf \n with Ease",
    highlight: "with Ease",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#FFFFFF",
    highlightColor: "#FFBE2E",
    content:
      "Depoter’s omnichannel fulfillment model connects your brand to modern retail networks across the region. Our B2B fulfillment solutions combine technology, compliance, and efficient delivery systems to help you meet every retailer’s unique requirements.",
    contentColor: "#FFFFFF",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
  },
  scalabilitygrowth: {
    title: "Scalability That Supports Long- \n Term B2B Growth",
    highlight: "B2B Growth",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#000000",
    highlightColor: "#FFBE2E",
  },
  advancetechnology: {
    title: "Advanced Technology That \n Powers Modern B2B Fulfillment",
    highlight: "B2B Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#000000",
    highlightColor: "#FFBE2E",
  },
  defineeverytechnology: {
    title: "Define Every \n Experience",
    highlight: "Experience",
    titleColor: "#FFFFFF",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#FFBE2E",
    className: "text-center md:text-left",
  },
  expandbuisness: {
    title: "Expand Your Business\n Across Every Channel",
    highlight: "Every Channel",
    titleColor: "#212121",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#FFBE2E",
    className: "text-center lg:text-left",
  },
  endtoend: {
    title: "End-to-End Return Management \n Built for B2B Precision",
    highlight: "B2B Precision",
    titleColor: "#212121",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#FFBE2E",
    className: "text-center",
  },
  moderncommercedeliveries: {
    title: "A Scalable Delivery Network Bult \n for ",
    highlight: "Modern Commerce",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
    content: (
      <>
        Logistics is the backbone of any successful brand in the Middle East. At
        Depoter, our <strong>delivery network</strong> is not just about moving
        boxes; it’s about <strong>operational excellence</strong>. We have built
        a strong infrastructure that covers:
      </>
    ),
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
  },
  deliverysolution: {
    title: "Domestic Delivery Solutions: \n",
    highlight: "Speed Tiers for Every Need",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
    content:
      "In the UAE, one size does not fit all. Your customers demand choices, and our ecommerce delivery services provide exactly that.",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
    button: {
      text: "Choose Your Delivery Speed",
      link: "#",
      className: "px-6 sm:px-12 py-3.5 mt-6",
    },
  },
  crossborderdelivery: {
    title: "Cross-Border\n Delivery Solutions:\n  ",
    highlight: "Expanding Across\n the GCC & Beyond",
    titleTag: "h2",
    titleSize: "text-[28px] sm:text-[36px] md:text-[32px] lg:text-[46px]",
    titleColor: "#FFFFFF",
    highlightColor: "#ffbe2e",
    content:
      "Don't let borders stop your growth. Our cross-border delivery solutions make shipping to international markets as simple as a local delivery, powered by operational excellence and seamless logistics.",
    contentWidth: "w-full",
    contentAlign: "left",
    contentSize:
      "text-[1rem] sm:text-[1.125rem] md:text-[1rem] lg:text-[1.3rem]",
    contentColor: "#FFFFFF",
    button: {
      text: "Start Shipping Globally Today",
      link: "#",
      className: "px-6 sm:px-12 py-3.5 mt-6",
    },
  },
  deliverycapabilities: {
    title: "Specialized ",
    highlight: "Delivery Capabilites",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
    content:
      "Some products require precision handling beyond standard courier services. We specialize in managing high-stakes categories with specific environmental and safety requirements:",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
    button: {
      text: "Integrate Your Store with Our Tech",
      link: "#",
      className: "px-6 sm:px-12 py-3.5 mt-6",
    },
  },
  deliveryservices: {
    title: "Value-Added ",
    highlight: "Delivery Services",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
    content:
      "We support your deliveries with additional services that improve customer experience and make your operations easier.",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
  },
  whychoosedeliveryservice: {
    title: "Why Choose ",
    highlight: "Depoter Delivery Services",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#FFFFFF",
    highlightColor: "#ffbe2e",
    content:
      "Choosing the right delivery partner can directly impact your customer experience and business growth.",
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
    contentColor: "#FFFFFF",
  },
  deliveryoperations: {
    title: "Ready to Simplify ",
    highlight: "Your Delivery\n Operations?",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#FFFFFF",
    highlightColor: "#ffbe2e",
    content: (
      <>
        Don’t let delivery challenges slow down your growth. With the right
        system in place, you can ensure fast shipping, reliable service, and
        better customer experience.
        <br /> <br /> Depoter helps you manage deliveries efficiently so you can
        focus on scaling your business.
      </>
    ),
    contentWidth: "w-full md:w-3/4 lg:w-2/3",
    contentColor: "#FFFFFF",
    button: {
      text: "Talk to a Delivery Expert",
      link: "#",
      className: "px-6 sm:px-12 py-3.5 mt-6 bg-[#FFBE2E]",
    },
  },
  manageeverything: {
    title: "Manage Everything Without the\n",
    highlight: "Confusion",
    titleColor: "#ffffff",
    content:
      "Managing multiple systems can slow down your work. Connect everything in one place and run your operations smoothly without errors or delays.",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#FFBE2E",
    className: "text-center",
    contentColor: "#FFFFFF",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-5/7",
  },

  scaleyourbusiness: {
    title: "Scale Your Operations with a\n",
    highlight: "Reliable Logistics Partner",
    titleColor: "#ffffff",
    content:
      "Don't let logistics hold your business back. Depoter provides the infrastructure, tech, and experts you need to win the UAE market.",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#FFBE2E",
    className: "text-center",
    contentColor: "#FFFFFF",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
    contentWidth: "w-full md:w-3/4 lg:w-3/5",
  },
};
