export const titleContentConfig = {
  services: {
    title: "Dedicated Fulfillment Solutions\n",
    highlight: "That Power Your Growth",
    content: "",
    titleTag: "h2",
    contentTag: "p",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[1.125rem]",
    titleColor: "#212121",
    contentColor: "#4A4A4A",
  },

  brand: {
    title: "Trusted by 1,100+ fast-growing brands",
    highlight: "1,100+",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
  },

  WhyChoose: {
    title: "Why Leading Brands Trust Depoter",
    highlight: "Depoter",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },

  Scalability: {
    title: "Scalability You Can Measure",
    highlight: "Measure",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  Howtowork: {
    title: "How Depoter Works",
    highlight: "Works",
    content:
      "Our connected process links your store, organizes your inventory, and delivers your orders quickly and accurately without operational complexity.",
    titleTag: "h2",
    contentTag: "p",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[1.125rem]",
    titleColor: "#212121",
    contentColor: "#000000",
  },
  buildtohandle: {
    title: "Built to Handle What You Sell",
    highlight: "Sell",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  global: {
    title: "Global Network of Fulfilment Centres",
    highlight: "Fulfilment Centres",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  insights: {
    title: "Insights from the Fulfillment Floor",
    highlight: "Fulfillment Floor",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  testimonials: {
    title: "Deeds Over Words",
    highlight: "Over Words",
    content: "What Our Clients Say",
    titleTag: "h2",
    contentTag: "h3",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    highlightColor: "#ffbe2e",
    contentSize: "text-[2rem]",
    titleColor: "#212121",
    contentColor: "#212121",
  },
  case: {
    title: "Delivered by Depoter",
    highlight: "Depoter",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  buildtohandleservice: {
    title: "Built to Handle What You Sell",
    highlight: "You Sell",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  Fulfillmentcenter: {
    title: "How Orders Move Through Our\n D2C Fulfillment Center",
    highlight: "D2C Fulfillment Center",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  easyreturns: {
    title: "Easy Returns and Exchanges",
    highlight: "and Exchanges",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  flexible: {
    title: " The Pillars of Fast and Flexible\n D2C Fulfillment",
    highlight: "D2C Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  Businessinsync: {
    title: "Integration That Keeps Your \n Business in Sync",
    highlight: "Business in Sync",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
    content:
      "Our platform integrates with leading eCommerce platforms, marketplaces, and shipping providers, automating order flow, inventory updates, and shipment tracking.",
    contentTag: "p",
    contentSize: "text-[1.125rem]",
    contentColor: "#FFFFFF",
  },
  Crossdocking: {
    title: "Crossdocking \n for Rapid ",
    highlight: "D2C \n Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  whychoosedepoter: {
    title: "Why Choose Depoter \n for ",
    highlight: "Freezone \n Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.7rem,1.2rem+1vw,2.7rem)]",
    titleColor: "#ffffff",
    highlightColor: "#ffbe2e",
  },
  b2bgradient: {
    title: "The Numbers That Define Us",
    highlight: "Define Us",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  smarttechnology: {
    title: "Smart Technology That \n Simplifies Every B2B Order",
    highlight: "B2B Order",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  flexiblestorage: {
    title: "Flexible Storage Solutions \n for Every Product Type",
    content:
      "Our warehouse facilities are equipped to manage all types of goods under precise environmental conditions. Our warehouse services include temperature-controlled zones, chiller storage, and compliance-ready facilities for specialized products.",
    highlight: "Product Type",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
    contentColor: "#000000",
  },
  fasterexpansion: {
    title: "Your Gateway to Duty-Free Storage \n and Faster GCC Expansion",
    highlight: "Faster GCC Expansion",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
  },
  managemesaurment: {
    title: "Manage Multiple Units of \n Measurement with Total Control",
    highlight: "Total Control",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    titleColor: "#212121",
    highlightColor: "#ffbe2e",
    content:
      "Our advanced inventory management system is designed for flexibility and accuracy. It handles multiple measurement levels seamlessly so that you can sell and ship products in any format without manual conversions.",
    contentColor: "#000000",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
  },
  deliverretail: {
    title: "Deliver to Every Retail Shelf \n with Ease",
    highlight: "with Ease",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    titleColor: "#FFFFFF",
    highlightColor: "#FFBE2E",
    content:
      "Depoter’s omnichannel fulfillment model connects your brand to modern retail networks across the region. Our B2B fulfillment solutions combine technology, compliance, and efficient delivery systems to help you meet every retailer’s unique requirements.",
    contentColor: "#FFFFFF",
    contentTag: "h3",
    contentSize: "text-[1.3rem]",
  },
  scalabilitygrowth: {
    title: "Scalability That Supports Long- \n Term B2B Growth",
    highlight: "B2B Growth",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    titleColor: "#000000",
    highlightColor: "#FFBE2E",
  },
  advancetechnology: {
    title: "Advanced Technology That \n Powers Modern B2B Fulfillment",
    highlight: "B2B Fulfillment",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    titleColor: "#000000",
    highlightColor: "#FFBE2E",
  },
  defineeverytechnology: {
    title: "Define Every \n Experience",
    highlight: "Experience",
    titleColor: "#FFFFFF",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    highlightColor: "#FFBE2E",
    className: "text-center md:text-left",
  },
  expandbuisness: {
    title: "Expand Your Business\n Across Every Channel",
    highlight: "Every Channel",
    titleColor: "#212121",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    highlightColor: "#FFBE2E",
    className: "text-center lg:text-left",
  },
  endtoend: {
    title: "End-to-End Return Management \n Built for B2B Precision",
    highlight: "B2B Precision",
    titleColor: "#212121",
    titleTag: "h2",
    titleSize: "text-[clamp(1.5rem,1rem+2vw,3rem)]",
    highlightColor: "#FFBE2E",
    className: "text-center",
  },
};
