"use client";

const steps = [
  {
    title: "Start the Process",
    desc: "A return label is generated by the customer through a branded portal or by the seller’s service team. The customer packs the items securely and ships them using the prepaid label.",
    icon: "/return-exchange-1.svg",
  },
  {
    title: "Return Handling",
    desc: "Returned parcels are received at the fulfillment center and registered in the system for tracking and verification.",
    icon: "/return-exchange-2.svg",
  },
  {
    title: "Quality Check",
    desc: "Each product is inspected and graded by the warehouse team using a defined checklist to confirm its resale condition.",
    icon: "/return-exchange-3.svg",
  },
  {
    title: "Next Action",
    desc: "Based on the inspection outcome, goods are either restocked, sent back to the seller for review, or marked for disposal.",
    icon: "/return-exchange-4.svg",
  },
  {
    title: "Refund Process",
    desc: "Once approved, the order is processed for a refund. The seller issues a full or partial refund, store credit, or gift card to the customer.",
    icon: "/return-exchange-5.svg",
  },
  {
    title: "Generate Reports",
    desc: "Comprehensive reports are generated automatically, capturing carrier pickups, delivery updates, item statuses, and overall return insights.",
    icon: "/return-exchange-6.svg",
  },
];

export default function ReturnNExchangeCard() {
  return (
    <div className="max-w-[1100px] mx-auto">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-x-12 gap-y-5 lg:gap-y-16 auto-rows-fr relative">
        {steps.map((step, i) => (
          <div
            key={i}
            className="flex flex-col items-center lg:items-start gap-5 relative h-auto lg:h-[460px]"
          >
            {/* ICON CARD */}
            {/* ICON */}
            <div className="relative flex items-center justify-center w-52 h-52">
              {/* Oval background */}
              <div className="absolute w-50 h-52 mt-10  bg-[#ffffff] rounded-full rotate-x-[125deg]" />

              {/* Image */}
              <img
                src={step.icon}
                alt=""
                className="relative z-10 w-44 h-44 object-contain"
              />
            </div>

            {/* TEXT */}
            <div className="w-full lg:w-[330px] text-center lg:text-left mt-10">
              <h3 className="text-xl font-bold text-[white] mb-7">
                {step.title}
              </h3>
              <p className="text-lg text-[white] font-light leading-relaxed">
                {step.desc}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
